### PR TITLE
Clearing response before redirects & bit of ReSharper refactor code

### PR DESCRIPTION
**Pull request by dcsanabria**
Clearing Response

### CODE REVIEW

**Comment by braathen** [comment]
I'm not a fan of those reshaper refactoring changes, can you please remove those and only keep the response clearing? Thanks!

**Comment by dcsanabria** [comment]
I just left the Response.Clear before the redirect.

Thanks for this project, is very useful for our company.

**Comment by braathen** [comment]
Thank you... :)

**Comment by dcsanabria** [comment]
@braathen is it possible to upgrade the nuget package with this small change?

**Comment by braathen** [comment]
I don't have any possibility to do that at the moment as I currently don't have a Windows development environment. I can make you a package co-owner if you want to do it?

**Comment by dcsanabria** [comment]
That sounds good I can do that.

**Comment by braathen** [comment]
Great! So create an account, send me the userid and I'll give you access, you can email me at firstname dot lastname at gmail dot com.

**Pull request merged**
