### PR TITLE
Certificate name and location are now configurable.

### PR DESCRIPTION
**Pull request by josemalonsom**
It would be nice if you could change certificate name and location.

### CODE REVIEW

**Comment by braathen** [comment]
Thank you, this has been a long overdue and needed fix..

**Comment by josemalonsom** [comment]
@braathen is it possible to upgrade the nuget package with these changes?

**Comment by braathen** [comment]
yes, will do tomorrow... sorry about the delay.

**Comment by josemalonsom** [comment]
don't worry, thank you very much.

**Pull request merged**
